#! /usr/bin/env bash
#
# create a skeleton UPS setup for genie_phyopt
#    this provides an area to put a UserPhysicsOptions.xml
#
#       ./make_skeleton <version> [<qualifier>]
# e.g.  ./make_skeleton v3665 dkcharmtau
#
product="genie_phyopt"
version=""         # like v3665
qual="dkcharmtau"  # use something else for special cases (modified MA, etc)
flavor="NULL"      # UserPhysicsOptions.xml file don't depend on OS flavor

if [ -z "$1" ]; then
  echo "You must supply a version"
  exit
fi
version=$1

if [ -n "$2" ]; then qual="$2"; fi

# odd case for .version file if NULL, examples have trailing _
flavorvf=${flavor}
if [ "$flavor" == "NULL" ]; then flavorvf="NULL_"; fi


#echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
echo "prepare to generate ups framework for"
echo "   setup ${product} ${version} -f ${flavor} -q ${qual}"
#echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"

for p in ${version}/${flavor}/${qual}/ups \
         ${version}.version
do
  if [ ! -d $p ]; then mkdir -p $p; fi
done

# make a symlink to the script that can create a UserPhysicsOptions.xml
# file that turns on decays for charm and tau.  This can be the final
# product or a starting point for further modifications
here=`pwd`
cd ${version}/${flavor}/${qual}
echo ln -s ../../../make_dkcharmtau_phyopt .
ln -s ../../../make_dkcharmtau_phyopt .
cd $here

tableFile=${version}/${flavor}/${qual}/ups/${product}.table
versionFile=${version}.version/${flavorvf}

#
# create the table file
#
if [ ! -f ${tableFile} ]; then
cat > ${tableFile} <<EOF
File=Table
Product=${product}
#*************************************************
# Starting Group definition

Group:

Flavor=${flavor}
Qualifiers="${qual}"

Common:
   Action=setup
      proddir()
      setupenv()
      envSet(GENIEPHYOPTPATH,\${UPS_PROD_DIR})
      pathAppend(GXMLPATH,  \${UPS_PROD_DIR})

End:
# End Group definition
#*************************************************
EOF
else
  echo "!!!!!  ${tableFile} exists, will not overwrite -- you must hand edit to add \"${qual}\""
fi

#
# create the version file, if it doesn't exist
#
if [ ! -f ${versionFile} ]; then
cat > ${versionFile} <<EOF
FILE = version
PRODUCT = ${product}
VERSION = ${version}

#*************************************************
EOF
fi

iam=`whoami`
if [ "$iam" == "nusoft" ]; then
  altiam=`klist | grep "Default principal" | cut -d':' -f2 | cut -d'@' -f1 | tr -d ' ' `
  if [ -n "$altiam" ]; then
    iam=${altiam}
    echo "i am \"${iam}\""
  fi
fi
nowGMT=`date -u "+%Y-%m-%d %H:%M:%S"`

nf=`grep QUALIFIERS ${versionFile} | grep -c \"${qual}\"`
if [ $nf -ne 0 ]; then
  echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
  echo "${versionFile} already has an entry for \"${qual}\""
  echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
else
#
# add this version to the version file
#
cat >> ${versionFile} <<EOF
#
FLAVOR = ${flavor}
QUALIFIERS   = "${qual}"
  DECLARER   = ${iam}
  DECLARED   = ${nowGMT} GMT
  MODIFIER   = ${iam}
  MODIFIED   = ${nowGMT} GMT
  PROD_DIR   = ${product}/${version}/${flavor}/${qual}
  UPS_DIR    = ups
  TABLE_FILE = ${product}.table
#
#*************************************************
EOF
fi

# end-of-script
