#! /usr/bin/env bash
# (checkout and) build dk2nu package
#
#  * Assumes that 'dk2nu' has been checked out and 
#    lives in ../source/dk2nu, while we're sitting in $DK2NU_FQ_DIR
#  * Assumes that GENIE (and thus ROOT) or just ROOT have been setup
#  * $ROOTSYS must point to the ROOT area
#  * If building against GENIE then $GENIE should point to the top of
#    the GENIE directory structure checked out from SVN
#  * Assumes that if using a 'gcc' other than the native one, it has been setup
#  * Assumes 'cmake' is available  (e.g. setup cmake )

#
b0=`basename $0`
export HERE=`pwd`
#
#
whichcm=`which cmake 2>/dev/null`
cstatus=$?
if [ $cstatus -ne 0 ]; then
  echo "cmake not available?"
  exit 1
fi
echo "using $whichcm"

if [ ! -d ../source/dk2nu ]; then
  echo "dk2nu directory not found?  did you check it out from SVN?"
  exit 1
fi

if [ "$1" == "NOGENIE" ]; then
  GENIEOPT="-DWITH_GENIE=OFF"
fi
if [ "$1" == "USEGCC" ]; then
  COMPILEROPT="-DCMAKE_CXX_COMPILER=`which g++` -DCMAKE_C_COMPILER=`which gcc`"
fi


export DK2NU_DIR=${HERE}
export DK2NU=${DK2NU_DIR}

mkdir dk2nu-build
cd $HERE/dk2nu-build

arch=`uname -s`
if [ "$arch" == "Darwin" ]; then
  MACEXTRA="env CC=gcc CXX=g++ FC=gfortran"
fi
CMD="${MACEXTRA} cmake ${COMPILEROPT} ${GENIEOPT} -DCMAKE_INSTALL_PREFIX:PATH=$DK2NU ../../source/dk2nu"

echo $CMD
     $CMD
gmake all install

cd $HERE
#rm -r dk2nu-build

if [ "$arch" == "Darwin" ]; then
# for now install_name_tool seems to be a problem on mac os x
  cd $HERE
  cp dk2nu-build/lib/libdk2nu* ${DK2nU_LIB}
fi


genie -b -q "$DK2NU/scripts/load_dk2nu.C(true,true,true)"
#
# end-of-script
